name: Tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.2
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "test"
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@master
      - name: Install library dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
          nodejs \
          ruby-dev \
          postgresql-client
      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: 3.1.2
          bundler-cache: true
          bundler: 2.3.7
      - name: Create database
        run: |
          export RAILS_ENV=test
          cp database.ci.yml database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
      - name: Run tests
        id: rspec-test
        run: |
          export RAILS_ENV=test
          bundle exec rspec